on: 
  push:
    branches:
      - main
name: Deploy Flutter Web App
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
     # ! 1
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
     # ! 2
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'
        channel: stable
        architecture: x64
        cache: false
        pub-cache-path: default
        dry-run: false
     # ! 3
     # ! 4
    - name: flutter pub get
      run: flutter pub get
     # ! 5
    - name: Build web
      run: flutter build web  
     # !
    - name: 📂 deploy build web
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.aquan.website
        username:  u943485201
        password:  Coder1632001@
        protocol: "ftp" 
        port: 21  
        server-dir: /domains/aquan.website/public_html/test/azwag_dash
        local-dir: ./build/web/
