on: 
  push:
    branches:
      - main
name: Deploy Flutter Web App
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
     # 1. Checkout the latest code
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

     # 2. Set up Flutter with Dart >= 3.5.0
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0' # Use Flutter version with Dart >= 3.5.0
        channel: stable
        architecture: x64

     # 3. Install dependencies
    - name: flutter pub get
      run: flutter pub get

     # 4. Build the web application
    - name: Build web
      run: flutter build web  

     # 5. Deploy the web build via FTP
    - name: 📂 Deploy build web
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.aquan.website
        username:  u943485201
        password:  Coder1632001@
        protocol: "ftp" 
        port: 21  
        server-dir: /domains/aquan.website/public_html/test/azwag_dash
        local-dir: ./build/web/
